[tool.poetry]
name = "dz10"
version = "0.1.0"
description = ""
authors = ["bobantonbob <130400459+bobantonbob@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.3"
<<<<<<< HEAD
pymongo = "3.11.0"
=======
pymongo = "^4.6.2"
>>>>>>> origin/master


[build-system]
requires = ["poetry-core"]
<<<<<<< HEAD
build-backend = "poetry.cor
=======
build-backend = "poetry.core.masonry.api"
>>>>>>> origin/master
